---
AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - '_snippets/**/*.rb'

# ignore block length in non-production code
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

# allow unsafe YAML loading in non-production code
Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented