---
development:
  # Infrastructure
  API_HOST: http://localhost:9090

test:
  # Infrastructure
  API_HOST: http://localhost:9090

app_test:
  # Application
  APP_HOST: http://localhost:9000
  # Infrastructure
  APP_HOST: http://localhost:9090

production:
  # Infrastructure
  REPOSTORE_PATH: app/infrastructure/git/repostore
  API_HOST: https://codepraise-api.herokuapp.com